import type { Job, Candidate } from "./types";

// 30 illustrative jobs across crypto + finance.
// Employers and details are plausible stand-ins — treat as demo data, not live listings.

const now = new Date();
const daysAgo = (n: number) =>
  new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString();

export const SEED_JOBS: Job[] = [
  // --- CRYPTO ------------------------------------------------------------
  {
    id: "job_crypto_001",
    title_raw: "Senior Protocol Engineer",
    title_normalized: "Senior Protocol Engineer",
    employer: "Uniswap Labs",
    employer_category: "DeFi protocol (Paradigm-backed)",
    domain: "crypto:defi",
    function: "engineering",
    seniority: "ic5",
    tech_stack: ["Solidity", "Foundry", "TypeScript", "Rust"],
    description:
      "Design and ship the next iteration of Uniswap's AMM protocol. Own core smart contract systems from design through audit. Work directly with protocol research and security teams.",
    base_min: 220000, base_max: 320000,
    bonus_pct_target: 20, token_pct_target: 40,
    carry_or_equity_pct: null, vesting_years: 4, cliff_months: 12,
    location: "Remote (US/EU)", remote_policy: "remote-global",
    jurisdiction_required: "global", visa_sponsored: false, regulated: false,
    stage: "series-b", team_size_band: "50-200", aum_usd: null,
    source_url: "https://uniswap.org/careers",
    source_channel: "vc-portfolio",
    date_posted: daysAgo(3), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_002",
    title_raw: "Senior Rust Engineer — MEV Infrastructure",
    title_normalized: "Senior Rust Engineer",
    employer: "Jump Crypto",
    employer_category: "Crypto-native trading firm",
    domain: "crypto:infra",
    function: "engineering",
    seniority: "ic6",
    tech_stack: ["Rust", "C++", "Solana", "EVM"],
    description:
      "Build high-performance infrastructure for on-chain trading and MEV. Work with researchers on novel blockspace-level strategies. Low-latency systems experience strongly preferred.",
    base_min: 280000, base_max: 420000,
    bonus_pct_target: 80, token_pct_target: 20,
    carry_or_equity_pct: null, vesting_years: 4, cliff_months: 12,
    location: "Chicago / NYC / Remote", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: false,
    stage: "public", team_size_band: "200+", aum_usd: null,
    source_url: "https://jumpcrypto.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(8), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_crypto_003",
    title_raw: "Quantitative Developer",
    title_normalized: "Quant Developer",
    employer: "Wintermute",
    employer_category: "Crypto market maker",
    domain: "crypto:trading",
    function: "quant-research",
    seniority: "ic5",
    tech_stack: ["Python", "C++", "kdb+", "Rust"],
    description:
      "Build and extend algorithmic market-making strategies across centralized and decentralized exchanges. Work with quant researchers on alpha, risk, and execution.",
    base_min: 200000, base_max: 300000,
    bonus_pct_target: 120, token_pct_target: 0,
    carry_or_equity_pct: 0.25, vesting_years: 4, cliff_months: 12,
    location: "London", remote_policy: "hybrid",
    jurisdiction_required: "uk", visa_sponsored: true, regulated: true,
    stage: "public", team_size_band: "200+", aum_usd: null,
    source_url: "https://wintermute.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(12), date_last_seen: daysAgo(1), is_open: true, employer_verified: true,
  },
  {
    id: "job_crypto_004",
    title_raw: "L2 Core Protocol Engineer",
    title_normalized: "L2 Protocol Engineer",
    employer: "Offchain Labs (Arbitrum)",
    employer_category: "L2 protocol team",
    domain: "crypto:l2",
    function: "engineering",
    seniority: "ic6",
    tech_stack: ["Go", "Rust", "Solidity", "EVM"],
    description:
      "Own core sequencer and bridge components for Arbitrum. Deep understanding of EVM and rollup architecture required.",
    base_min: 240000, base_max: 340000,
    bonus_pct_target: 20, token_pct_target: 50,
    carry_or_equity_pct: null, vesting_years: 4, cliff_months: 12,
    location: "Remote (Global)", remote_policy: "remote-global",
    jurisdiction_required: "global", visa_sponsored: false, regulated: false,
    stage: "series-c", team_size_band: "200+", aum_usd: null,
    source_url: "https://arbitrum.io/careers",
    source_channel: "vc-portfolio",
    date_posted: daysAgo(20), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_005",
    title_raw: "Applied Cryptographer (ZK)",
    title_normalized: "Applied Cryptographer",
    employer: "Optimism Foundation",
    employer_category: "L2 protocol team",
    domain: "crypto:l2",
    function: "engineering",
    seniority: "ic7",
    tech_stack: ["Rust", "Circom", "Halo2", "Go"],
    description:
      "Research and implement ZK proving systems for OP Stack. Strong background in applied cryptography, PhD preferred but not required.",
    base_min: 260000, base_max: 380000,
    bonus_pct_target: 15, token_pct_target: 60,
    carry_or_equity_pct: null, vesting_years: 4, cliff_months: 12,
    location: "Remote (Global)", remote_policy: "remote-global",
    jurisdiction_required: "global", visa_sponsored: false, regulated: false,
    stage: "dao", team_size_band: "50-200", aum_usd: null,
    source_url: "https://optimism.io/careers",
    source_channel: "dao-forum",
    date_posted: daysAgo(5), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_006",
    title_raw: "Senior Full-Stack Engineer",
    title_normalized: "Senior Full-Stack Engineer",
    employer: "Farcaster",
    employer_category: "Crypto social (a16z-backed)",
    domain: "crypto:application",
    function: "engineering",
    seniority: "ic5",
    tech_stack: ["TypeScript", "React", "Rust", "Postgres"],
    description:
      "Build client-facing surfaces for the Farcaster protocol. Own features from design through ship. Strong frontend + backend generalist needed.",
    base_min: 200000, base_max: 290000,
    bonus_pct_target: 15, token_pct_target: 30,
    carry_or_equity_pct: 0.1, vesting_years: 4, cliff_months: 12,
    location: "Los Angeles / Remote (US)", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: false, regulated: false,
    stage: "series-a", team_size_band: "10-50", aum_usd: null,
    source_url: "https://farcaster.xyz/careers",
    source_channel: "farcaster",
    date_posted: daysAgo(6), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_007",
    title_raw: "Protocol Security Researcher",
    title_normalized: "Security Researcher",
    employer: "Paradigm",
    employer_category: "Crypto VC / research",
    domain: "crypto:security",
    function: "engineering",
    seniority: "ic7",
    tech_stack: ["Solidity", "Foundry", "Yul", "Rust"],
    description:
      "Research and disclose vulnerabilities across DeFi. Work with portfolio companies on audits, design reviews, and incident response.",
    base_min: 300000, base_max: 500000,
    bonus_pct_target: 50, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 4, cliff_months: 12,
    location: "NYC / SF", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: false,
    stage: "fund", team_size_band: "10-50", aum_usd: 13000000000,
    source_url: "https://paradigm.xyz/careers",
    source_channel: "vc-direct",
    date_posted: daysAgo(14), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_crypto_008",
    title_raw: "Founding Protocol Engineer",
    title_normalized: "Founding Protocol Engineer",
    employer: "Symbiotic (stealth)",
    employer_category: "Restaking protocol (Polychain-backed)",
    domain: "crypto:defi",
    function: "engineering",
    seniority: "ic6",
    tech_stack: ["Solidity", "Rust", "Foundry"],
    description:
      "Join as one of the first five engineers on a shared-security protocol. Own significant surface area; expect to publish specs and ship audited production code.",
    base_min: 210000, base_max: 300000,
    bonus_pct_target: 0, token_pct_target: 100,
    carry_or_equity_pct: 1.5, vesting_years: 4, cliff_months: 12,
    location: "Remote (Global)", remote_policy: "remote-global",
    jurisdiction_required: "global", visa_sponsored: false, regulated: false,
    stage: "seed", team_size_band: "1-10", aum_usd: null,
    source_url: "https://careers.example.com/symbiotic",
    source_channel: "vc-portfolio",
    date_posted: daysAgo(2), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_009",
    title_raw: "Smart Contract Security Engineer",
    title_normalized: "Smart Contract Security Engineer",
    employer: "Coinbase (Base)",
    employer_category: "Public crypto exchange",
    domain: "crypto:l2",
    function: "engineering",
    seniority: "ic5",
    tech_stack: ["Solidity", "Foundry", "Go", "TypeScript"],
    description:
      "Secure the Base L2 ecosystem. Review internal and partner contracts; run bug bounty triage; build automated tooling.",
    base_min: 230000, base_max: 310000,
    bonus_pct_target: 25, token_pct_target: 0,
    carry_or_equity_pct: 0.05, vesting_years: 4, cliff_months: 12,
    location: "Remote (US)", remote_policy: "remote-regional",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "public", team_size_band: "200+", aum_usd: null,
    source_url: "https://coinbase.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(10), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_crypto_010",
    title_raw: "Head of Growth",
    title_normalized: "Head of Growth",
    employer: "Agora (stablecoin issuer)",
    employer_category: "Fintech/crypto (a16z-backed)",
    domain: "crypto:defi",
    function: "business",
    seniority: "m3",
    tech_stack: [],
    description:
      "Own growth, partnerships, and distribution for a regulated stablecoin issuer. Prior experience scaling a regulated financial product required.",
    base_min: 220000, base_max: 320000,
    bonus_pct_target: 30, token_pct_target: 20,
    carry_or_equity_pct: 0.4, vesting_years: 4, cliff_months: 12,
    location: "NYC / Remote", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: false, regulated: true,
    stage: "series-a", team_size_band: "10-50", aum_usd: null,
    source_url: "https://agora.finance/careers",
    source_channel: "vc-portfolio",
    date_posted: daysAgo(18), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_011",
    title_raw: "Senior Data Engineer — On-Chain Analytics",
    title_normalized: "Senior Data Engineer",
    employer: "Chainalysis",
    employer_category: "Blockchain data analytics",
    domain: "crypto:analytics",
    function: "data",
    seniority: "ic5",
    tech_stack: ["Python", "Spark", "Snowflake", "SQL"],
    description:
      "Own large-scale on-chain data pipelines. Work with compliance and research teams to build features and datasets used by governments and top financial institutions.",
    base_min: 190000, base_max: 260000,
    bonus_pct_target: 15, token_pct_target: 0,
    carry_or_equity_pct: 0.02, vesting_years: 4, cliff_months: 12,
    location: "NYC / Remote (US)", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "series-d-plus", team_size_band: "200+", aum_usd: null,
    source_url: "https://chainalysis.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(22), date_last_seen: daysAgo(1), is_open: true, employer_verified: true,
  },
  {
    id: "job_crypto_012",
    title_raw: "Quant Researcher — Systematic Crypto",
    title_normalized: "Quant Researcher",
    employer: "Cumberland (DRW)",
    employer_category: "Prop trading / crypto",
    domain: "crypto:trading",
    function: "quant-research",
    seniority: "ic6",
    tech_stack: ["Python", "C++", "kdb+"],
    description:
      "Develop and deploy systematic strategies across crypto derivatives and spot markets. PhD or equivalent rigor expected.",
    base_min: 250000, base_max: 350000,
    bonus_pct_target: 200, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "Chicago", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "propshop", team_size_band: "200+", aum_usd: null,
    source_url: "https://cumberland.io/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(7), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_crypto_013",
    title_raw: "DAO Operator / Governance Lead",
    title_normalized: "DAO Operator",
    employer: "Arbitrum Foundation",
    employer_category: "Protocol foundation",
    domain: "crypto:l2",
    function: "ops",
    seniority: "m2",
    tech_stack: [],
    description:
      "Drive governance coordination, delegate relations, and grant programs. Deep familiarity with on-chain governance mechanics required.",
    base_min: 180000, base_max: 240000,
    bonus_pct_target: 0, token_pct_target: 80,
    carry_or_equity_pct: null, vesting_years: 3, cliff_months: 12,
    location: "Remote (Global)", remote_policy: "remote-global",
    jurisdiction_required: "global", visa_sponsored: false, regulated: false,
    stage: "dao", team_size_band: "10-50", aum_usd: null,
    source_url: "https://arbitrum.foundation/careers",
    source_channel: "dao-forum",
    date_posted: daysAgo(16), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_014",
    title_raw: "Senior Developer Relations Engineer",
    title_normalized: "DevRel Engineer",
    employer: "Monad Labs",
    employer_category: "L1 protocol (Paradigm/Dragonfly-backed)",
    domain: "crypto:l1",
    function: "engineering",
    seniority: "ic5",
    tech_stack: ["Solidity", "Rust", "TypeScript"],
    description:
      "Lead developer advocacy and ecosystem growth for a parallelized L1. Write excellent code, docs, and onstage content.",
    base_min: 200000, base_max: 280000,
    bonus_pct_target: 0, token_pct_target: 80,
    carry_or_equity_pct: null, vesting_years: 4, cliff_months: 12,
    location: "Remote (Global)", remote_policy: "remote-global",
    jurisdiction_required: "global", visa_sponsored: false, regulated: false,
    stage: "series-a", team_size_band: "10-50", aum_usd: null,
    source_url: "https://monad.xyz/careers",
    source_channel: "vc-portfolio",
    date_posted: daysAgo(4), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },
  {
    id: "job_crypto_015",
    title_raw: "Senior ML Researcher",
    title_normalized: "ML Researcher",
    employer: "Dune",
    employer_category: "On-chain analytics platform",
    domain: "crypto:analytics",
    function: "data",
    seniority: "ic6",
    tech_stack: ["Python", "PyTorch", "Spark", "Rust"],
    description:
      "Apply ML to on-chain data at scale: entity clustering, transaction classification, anomaly detection. Own research from hypothesis to production deploy.",
    base_min: 230000, base_max: 320000,
    bonus_pct_target: 15, token_pct_target: 20,
    carry_or_equity_pct: 0.08, vesting_years: 4, cliff_months: 12,
    location: "Remote (Global)", remote_policy: "remote-global",
    jurisdiction_required: "global", visa_sponsored: false, regulated: false,
    stage: "series-b", team_size_band: "50-200", aum_usd: null,
    source_url: "https://dune.com/careers",
    source_channel: "vc-portfolio",
    date_posted: daysAgo(11), date_last_seen: daysAgo(0), is_open: true, employer_verified: false,
  },

  // --- FINANCE -----------------------------------------------------------
  {
    id: "job_finance_001",
    title_raw: "Trader / Developer",
    title_normalized: "Trader Developer",
    employer: "Jane Street",
    employer_category: "Quant trading / prop",
    domain: "finance:prop",
    function: "trading",
    seniority: "ic4",
    tech_stack: ["OCaml", "Python"],
    description:
      "Build and trade strategies across equities, options, ETFs, and FX. Rotational exposure across desks. Rigorous interview process; exceptional quant or engineering credentials expected.",
    base_min: 225000, base_max: 225000,
    bonus_pct_target: 250, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "propshop", team_size_band: "200+", aum_usd: null,
    source_url: "https://janestreet.com/join",
    source_channel: "employer-direct",
    date_posted: daysAgo(9), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_002",
    title_raw: "Senior Quantitative Researcher — US Equities",
    title_normalized: "Senior Quant Researcher",
    employer: "Citadel Global Equities",
    employer_category: "Multi-strategy hedge fund",
    domain: "finance:equities",
    function: "quant-research",
    seniority: "ic6",
    tech_stack: ["Python", "C++", "KX"],
    description:
      "Own research agenda for a pod within Global Equities. PhD-level statistical/ML background required. Access to institutional data and infrastructure.",
    base_min: 275000, base_max: 400000,
    bonus_pct_target: 400, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC / Chicago", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 65000000000,
    source_url: "https://citadel.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(6), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_003",
    title_raw: "ML Researcher — Systematic Strategies",
    title_normalized: "ML Researcher",
    employer: "Two Sigma",
    employer_category: "Systematic hedge fund",
    domain: "finance:systematic",
    function: "quant-research",
    seniority: "ic6",
    tech_stack: ["Python", "PyTorch", "C++"],
    description:
      "Apply deep learning to multi-asset systematic trading. Core research role reporting to senior partner. Publication-level research welcome.",
    base_min: 275000, base_max: 400000,
    bonus_pct_target: 250, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 60000000000,
    source_url: "https://twosigma.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(13), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_004",
    title_raw: "C++ Developer — Low Latency Systems",
    title_normalized: "Low Latency C++ Engineer",
    employer: "Hudson River Trading",
    employer_category: "HFT / prop",
    domain: "finance:hft",
    function: "engineering",
    seniority: "ic5",
    tech_stack: ["C++", "Linux", "FPGA"],
    description:
      "Build the trading systems that execute HRT's strategies. Microsecond matters. Deep C++, Linux internals, and optional FPGA experience.",
    base_min: 250000, base_max: 350000,
    bonus_pct_target: 300, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "propshop", team_size_band: "200+", aum_usd: null,
    source_url: "https://hudson-trading.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(2), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_005",
    title_raw: "Quantitative Analyst — Structured Credit",
    title_normalized: "Credit Quant Analyst",
    employer: "D. E. Shaw",
    employer_category: "Multi-strategy hedge fund",
    domain: "finance:credit",
    function: "quant-research",
    seniority: "ic5",
    tech_stack: ["Python", "C++", "SQL"],
    description:
      "Research and price structured credit strategies. PhD/Master's in quantitative field; familiarity with CDS, CLO, securitized products required.",
    base_min: 225000, base_max: 300000,
    bonus_pct_target: 200, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 60000000000,
    source_url: "https://deshaw.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(19), date_last_seen: daysAgo(1), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_006",
    title_raw: "Portfolio Manager — Equity L/S",
    title_normalized: "Portfolio Manager",
    employer: "Millennium Management",
    employer_category: "Multi-manager hedge fund",
    domain: "finance:equities",
    function: "trading",
    seniority: "m3",
    tech_stack: [],
    description:
      "Run a single-manager equity long/short book with established track record. Deployed seat with formula-based P&L participation.",
    base_min: 350000, base_max: 500000,
    bonus_pct_target: 500, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC / London", remote_policy: "onsite",
    jurisdiction_required: "global", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 70000000000,
    source_url: "https://mlp.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(27), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_007",
    title_raw: "Senior Quantitative Researcher",
    title_normalized: "Senior Quant Researcher",
    employer: "Point72 Cubist",
    employer_category: "Systematic fund within Point72",
    domain: "finance:systematic",
    function: "quant-research",
    seniority: "ic6",
    tech_stack: ["Python", "C++", "SQL"],
    description:
      "Own research for a systematic equity pod. Full production infrastructure; exceptional researchers fast-track to senior roles.",
    base_min: 275000, base_max: 400000,
    bonus_pct_target: 300, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 35000000000,
    source_url: "https://point72.com/cubist",
    source_channel: "employer-direct",
    date_posted: daysAgo(4), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_008",
    title_raw: "Senior Systematic Researcher — Global Macro",
    title_normalized: "Systematic Macro Researcher",
    employer: "AQR Capital",
    employer_category: "Systematic asset manager",
    domain: "finance:macro",
    function: "quant-research",
    seniority: "ic6",
    tech_stack: ["Python", "R", "SQL"],
    description:
      "Research systematic macro strategies across rates, FX, commodities. Publication-friendly environment; academic lineage welcomed.",
    base_min: 225000, base_max: 325000,
    bonus_pct_target: 150, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 3, cliff_months: 12,
    location: "Greenwich, CT", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 110000000000,
    source_url: "https://aqr.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(15), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_009",
    title_raw: "Software Engineer — Exchange Connectivity",
    title_normalized: "Exchange Connectivity Engineer",
    employer: "Jump Trading",
    employer_category: "Prop trading",
    domain: "finance:hft",
    function: "engineering",
    seniority: "ic4",
    tech_stack: ["C++", "Python", "Linux"],
    description:
      "Build and maintain exchange gateways and matching-engine-adjacent infra. Deep networking + C++ expertise. Competitive comp with strong junior ramp.",
    base_min: 200000, base_max: 270000,
    bonus_pct_target: 200, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "Chicago / NYC", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "propshop", team_size_band: "200+", aum_usd: null,
    source_url: "https://jumptrading.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(1), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_010",
    title_raw: "Quant Developer — High Frequency",
    title_normalized: "HFT Quant Developer",
    employer: "Tower Research Capital",
    employer_category: "HFT / prop",
    domain: "finance:hft",
    function: "engineering",
    seniority: "ic5",
    tech_stack: ["C++", "Python", "Kubernetes"],
    description:
      "Build strategy research and production systems for HFT. Microsecond-level performance work.",
    base_min: 230000, base_max: 320000,
    bonus_pct_target: 250, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "propshop", team_size_band: "200+", aum_usd: null,
    source_url: "https://tower-research.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(23), date_last_seen: daysAgo(1), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_011",
    title_raw: "Data Scientist — Alt Data Strategies",
    title_normalized: "Alt Data Scientist",
    employer: "Balyasny Asset Management",
    employer_category: "Multi-manager hedge fund",
    domain: "finance:discretionary",
    function: "data",
    seniority: "ic4",
    tech_stack: ["Python", "SQL", "Snowflake", "scikit-learn"],
    description:
      "Source, evaluate, and productize alternative datasets for fundamental equity and macro PMs. High bandwidth with investment teams.",
    base_min: 180000, base_max: 250000,
    bonus_pct_target: 120, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "NYC / Chicago", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 22000000000,
    source_url: "https://bam.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(17), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_012",
    title_raw: "Options Trader",
    title_normalized: "Options Trader",
    employer: "Akuna Capital",
    employer_category: "Options market maker",
    domain: "finance:prop",
    function: "trading",
    seniority: "ic4",
    tech_stack: ["Python", "C++"],
    description:
      "Trade options market-making strategies. Strong quantitative intuition and fast decision-making. Chicago floor culture.",
    base_min: 175000, base_max: 230000,
    bonus_pct_target: 250, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "Chicago", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "propshop", team_size_band: "200+", aum_usd: null,
    source_url: "https://akunacapital.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(21), date_last_seen: daysAgo(1), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_013",
    title_raw: "Investment Engineer",
    title_normalized: "Investment Engineer",
    employer: "Bridgewater Associates",
    employer_category: "Global macro hedge fund",
    domain: "finance:macro",
    function: "engineering",
    seniority: "ic5",
    tech_stack: ["Python", "Java", "SQL"],
    description:
      "Build analytical infrastructure for portfolio research. Work closely with investment associates. Bridgewater cultural fit is rigorous.",
    base_min: 200000, base_max: 280000,
    bonus_pct_target: 80, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 4, cliff_months: 12,
    location: "Westport, CT", remote_policy: "hybrid",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "fund", team_size_band: "200+", aum_usd: 160000000000,
    source_url: "https://bridgewater.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(25), date_last_seen: daysAgo(1), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_014",
    title_raw: "Senior Quantitative Trader",
    title_normalized: "Senior Quant Trader",
    employer: "Susquehanna International Group",
    employer_category: "Options market maker",
    domain: "finance:prop",
    function: "trading",
    seniority: "ic6",
    tech_stack: ["Python", "C++"],
    description:
      "Lead options market-making strategy for a specific market segment. SIG-pedigree preferred; strong game-theoretic thinking required.",
    base_min: 300000, base_max: 425000,
    bonus_pct_target: 400, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 0, cliff_months: 0,
    location: "Bala Cynwyd, PA", remote_policy: "onsite",
    jurisdiction_required: "us", visa_sponsored: true, regulated: true,
    stage: "propshop", team_size_band: "200+", aum_usd: null,
    source_url: "https://sig.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(8), date_last_seen: daysAgo(0), is_open: true, employer_verified: true,
  },
  {
    id: "job_finance_015",
    title_raw: "VP — FICC Strategist",
    title_normalized: "FICC Strategist",
    employer: "Goldman Sachs Global Markets",
    employer_category: "Investment bank",
    domain: "finance:banking",
    function: "quant-research",
    seniority: "m2",
    tech_stack: ["Python", "SQL"],
    description:
      "Cover rates and credit strategy for Goldman's FICC clients. Deliver written market views; speak at client events; collaborate with sales and trading.",
    base_min: 225000, base_max: 275000,
    bonus_pct_target: 120, token_pct_target: 0,
    carry_or_equity_pct: null, vesting_years: 3, cliff_months: 12,
    location: "NYC / London", remote_policy: "onsite",
    jurisdiction_required: "global", visa_sponsored: true, regulated: true,
    stage: "public", team_size_band: "200+", aum_usd: null,
    source_url: "https://goldmansachs.com/careers",
    source_channel: "employer-direct",
    date_posted: daysAgo(30), date_last_seen: daysAgo(2), is_open: true, employer_verified: true,
  },
];

// --- CANDIDATE PERSONAS ---------------------------------------------------

export const SEED_CANDIDATES: Candidate[] = [
  {
    id: "cand_bridge_001",
    display_name: "0xHaru",
    identity_mode: "pseudonym",
    headline:
      "Founding engineer at a DeFi protocol; 8 years across Solidity, Rust, and MEV. Curious about systematic crypto trading and quant-adjacent roles.",
    years_experience: 8,
    current_role: "Founding Protocol Engineer",
    current_employer: "(DeFi protocol, Paradigm-backed)",
    education: "BS Computer Science, UC Berkeley",
    linkedin_url: null,
    github_url: "https://github.com/0xharu",
    farcaster_handle: "haru",
    wallet_address: "0xharu.eth",
    domains_of_interest: ["crypto:defi", "crypto:infra", "crypto:trading", "finance:prop", "finance:hft"],
    functions: ["engineering", "quant-research"],
    seniority_band: "ic6",
    tech_stack: ["Solidity", "Rust", "TypeScript", "Foundry", "Python"],
    comp_floor_usd: 280000,
    jurisdiction_ok: ["global", "us", "eu", "uk"],
    remote_policy_ok: ["remote-global", "hybrid"],
    visa_needed: false,
    max_regulated_ok: true,
    weight_comp: 0.7,
    weight_domain_fit: 0.9,
    weight_team_quality: 0.95,
    weight_token_upside: 0.7,
    dealbreakers: ["onsite-only", "no token comp"],
    saved_job_ids: [],
    dismissed_job_ids: [],
  },
  {
    id: "cand_tradfi_001",
    display_name: "Priya Chen",
    identity_mode: "real",
    headline:
      "Quant researcher with 12 years at Goldman then Citadel US equities pod. Crypto-curious but only for institutionally credible teams.",
    years_experience: 12,
    current_role: "Senior Quantitative Researcher",
    current_employer: "Citadel Global Equities",
    education: "PhD Statistics, Stanford; BA Mathematics, Princeton",
    linkedin_url: "https://linkedin.com/in/priyachen",
    github_url: null,
    farcaster_handle: null,
    wallet_address: null,
    domains_of_interest: ["finance:systematic", "finance:equities", "crypto:trading", "finance:macro"],
    functions: ["quant-research"],
    seniority_band: "ic6",
    tech_stack: ["Python", "C++", "KX", "PyTorch"],
    comp_floor_usd: 400000,
    jurisdiction_ok: ["us"],
    remote_policy_ok: ["hybrid", "onsite"],
    visa_needed: false,
    max_regulated_ok: true,
    weight_comp: 0.9,
    weight_domain_fit: 0.85,
    weight_team_quality: 0.95,
    weight_token_upside: 0.3,
    dealbreakers: ["unregulated", "seed-stage"],
    saved_job_ids: [],
    dismissed_job_ids: [],
  },
  {
    id: "cand_finnative_001",
    display_name: "Marco Ferrari",
    identity_mode: "real",
    headline:
      "5 years at Jane Street across equities and options. Strong builder; interested in leaving pure prop for a crypto-native trading firm or early-stage protocol with real comp upside.",
    years_experience: 5,
    current_role: "Trader / Developer",
    current_employer: "Jane Street",
    education: "MEng Computer Science, MIT",
    linkedin_url: "https://linkedin.com/in/marcoferrari",
    github_url: "https://github.com/mferrari",
    farcaster_handle: "marco",
    wallet_address: null,
    domains_of_interest: ["crypto:trading", "crypto:defi", "crypto:infra", "finance:prop", "finance:hft"],
    functions: ["trading", "engineering", "quant-research"],
    seniority_band: "ic4",
    tech_stack: ["OCaml", "Python", "C++", "Rust"],
    comp_floor_usd: 300000,
    jurisdiction_ok: ["us", "uk"],
    remote_policy_ok: ["hybrid", "onsite", "remote-regional"],
    visa_needed: false,
    max_regulated_ok: true,
    weight_comp: 0.8,
    weight_domain_fit: 0.9,
    weight_team_quality: 0.9,
    weight_token_upside: 0.8,
    dealbreakers: ["no equity upside"],
    saved_job_ids: [],
    dismissed_job_ids: [],
  },
];
